import pandas as pd
df_roupas = pd.read_excel('vendas_roupas.xlsx')


print()
print(130 * '=')
print('                              Visão Geral da Planilha')
print(df_roupas)
print(130 * '=')
print()

print()
print(130 * '=')
print('                              Quantidade Total de peças vendidadas')
print(df_roupas['Unidades Vendidas'].sum())
print(130 * '=')
print()

print()
print(130 * '=')
print('                              Média dos preços')
print(df_roupas['Preço por Unidade (R$)'].mean())
print(130 * '=')
print()

print()
print(130 * '=')
print('                              Produto com maior faturamento')
print(df_roupas.loc[df_roupas['Faturamento Total (R$)'].idxmax(),'Produto'])
print(df_roupas.loc[df_roupas['Faturamento Total (R$)'].idxmax(),'Faturamento Total (R$)'])
print(df_roupas['Faturamento Total (R$)'].max())
print(130 * '=')
print()

print()
print(130 * '=')
print('                              Produto com menor faturamento')
print(df_roupas.loc[df_roupas['Faturamento Total (R$)'].idxmin(),'Produto'])
print(df_roupas.loc[df_roupas['Faturamento Total (R$)'].idxmin(),'Faturamento Total (R$)'])
print(df_roupas['Faturamento Total (R$)'].min())
print(130 * '=')
print()

print()
print(130 * '=')
print('                              Produtos com nivel de satisfação baixo')
print(df_roupas[df_roupas['Satisfação'] == 'Baixo'])
print(130 * '=')
print()

print()
print(130 * '=')
print('                               Produtos com faturamento acima da média')
media = df_roupas['Faturamento Total (R$)'].mean()
print(f'A média é de {media}.')
print(df_roupas[df_roupas['Faturamento Total (R$)'] >= media])
print(130 * '=')
print()

